In [68]:
import statsmodels.api as sm
import pandas as pd
from patsy import dmatrices
from statsmodels.stats.multicomp import pairwise_tukeyhsd, MultiComparison, tukeyhsd
from statsmodels.sandbox.stats.multicomp import multipletests
from statsmodels.stats.weightstats import ttest_ind
from statsmodels.sandbox.stats.multicomp import multipletests
import numpy as np
from statsmodels.stats.libqsturng import psturng
from statsmodels.formula.api import ols

# All topic test Exp2,Exp4a and Exp4b (PPV)

In [89]:
from numpy import std, mean, sqrt

#correct if the population S.D. is expected to be equal for the two groups.
def cohen_d(x,y):
    nx = len(x)
    ny = len(y)
    dof = nx + ny - 2
    d =(mean(x) - mean(y)) / sqrt(((nx-1)*std(x, ddof=1) ** 2 + (ny-1)*std(y, ddof=1) ** 2) / dof)
    if d < 0.20:
        effect = 'very small (Sawilowsky, 2009)'
    elif d < 0.5:
        effect = 'small (Cohen, 1988)'
    elif d < 0.8:
        effect = 'medium (Cohen, 1988)'
    elif d < 1.2:
        effect = 'large (Cohen, 1988)'
    elif d < 2:
        effect = 'very large (Sawilowsky, 2009)'
    else:
        effect = 'huge (Sawilowsky, 2009)'
    return d,effect

In [90]:
df = pd.read_csv('alltopics_forAnova.csv')

In [91]:
x = df[(df['typex']=='first')&(df['balance']==50)].PPV
y = df[(df['typex']=='last')&(df['balance']==50)].PPV
a1 = ttest_ind(x,y,alternative='larger')
print(a1)
print(cohen_d(x,y))

(3.2226457079770752, 0.00071910110285952676, 251.0)
(0.40524049000741369, 'small (Cohen, 1988)')


In [92]:
x = df[(df['typex']=='first')&(df['balance']==50)].Accuracy
y = df[(df['typex']=='last')&(df['balance']==50)].Accuracy
a2 = ttest_ind(x,y,alternative='larger')
print(a2)
print(cohen_d(x,y))

(2.6088017050289909, 0.0048155726290837154, 251.0)
(0.32805097956043971, 'small (Cohen, 1988)')


In [94]:
multipletests(a1[1],a2[1],method='holm')

(array([ True], dtype=bool),
 array([ 0.00481557]),
 0.0048155726290837197,
 0.0048155726290837154)

In [56]:
x = df[(df['typex']=='random')&(df['balance']==50)].Accuracy
y = df[(df['typex']=='last')&(df['balance']==50)].Accuracy
a1 = ttest_ind(x,y)
print(a1)
print(cohen_d(x,y))
a2 = ttest_ind(df[(df['typex']=='first')&(df['balance']==50)].Accuracy,df[(df['typex']=='last')&(df['balance']==50)].Accuracy,alternative='larger')
a2

(2.6088017050289909, 0.0048155726290837154, 251.0)

In [66]:
a3 = ttest_ind(df[(df['typex']=='random')&(df['balance']==50)].Accuracy,df[(df['typex']=='first')&(df['balance']==50)].Accuracy)
a3

(-0.70921263081935859, 0.4794433215235836, 132.0)

In [67]:
a4 = ttest_ind(df[(df['typex']=='random')&(df['balance']==50)].Accuracy,df[(df['typex']=='last')&(df['balance']==50)].Accuracy)
a4

(1.7587494227208926, 0.080836638558093601, 138.0)

In [59]:
multipletests([a1[1],a2[1],a3[1],a4[1]],method='holm')

(array([ True,  True, False, False], dtype=bool),
 array([ 0.0028764 ,  0.01444672,  0.21700087,  0.21700087]),
 0.012741455098566168,
 0.0125)

In [75]:
smp.ttest_power(0.2, nobs=60, alpha=0.1, alternative='two-sided')

0.45558175996348543

In [78]:
smp.ttest_power(, nobs=138, alpha=0.08)

/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/statsmodels/stats/power.py:63: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  pow_ = stats.nct._sf(crit_upp, df, d*np.sqrt(nobs))


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

considering all topics, first is better than last for 50-50 in both term of accuracy and PPV, while there is not enough evidence 

In [60]:
df = pd.read_csv('Exp2_forAnova.csv')

In [61]:
b1 = ttest_ind(df[(df['typex']=='first')&(df['balance']==50)].PPV,df[(df['typex']=='last')&(df['balance']==50)].PPV,alternative='larger')
b1

(2.3599183954989336, 0.010220051809051594, 90.0)

In [62]:
b2 = ttest_ind(df[(df['typex']=='first')&(df['balance']==50)].Accuracy,df[(df['typex']=='last')&(df['balance']==50)].Accuracy,alternative='larger')
b2

(1.6021061925946132, 0.056318165320166931, 90.0)

In [63]:
b3 = ttest_ind(df[(df['typex']=='random')&(df['balance']==50)].Accuracy,df[(df['typex']=='first')&(df['balance']==50)].Accuracy)
b3

(-0.80834313265678148, 0.42034751998311026, 132.0)

In [64]:
b4 = ttest_ind(df[(df['typex']=='random')&(df['balance']==50)].Accuracy,df[(df['typex']=='last')&(df['balance']==50)].Accuracy)
b4

(0.88286960004334025, 0.3788420865298312, 138.0)

In [65]:
multipletests([a1[1],a2[1],a3[1],a4[1],b1[1],b2[1],b3[1],b4[1]],method='holm')

(array([ True,  True, False, False, False, False, False, False], dtype=bool),
 array([ 0.00575281,  0.03370901,  0.43400175,  0.44571372,  0.06132031,
         0.28159083,  0.75768417,  0.75768417]),
 0.0063911509545450107,
 0.00625)

In [69]:
ttest_ind?